version: 2
updates:
  - package-ecosystem: "pip"
    directories:
      - "/"
      - "/{{ cookiecutter.project_slug }}"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore"
      include: "scope"
  - package-ecosystem: "github-actions"
    directories:
      - "/"
      - "/{{ cookiecutter.project_slug }}"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "ci"
      include: "scope"
